### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by Vaibhav-08** [samadii/MusicChannelManager#1]
I have added the bot token as required in the template but after deploying, it couldn't start. Following is the log:

2021-06-25T12:26:05.077817+00:00 heroku[worker.1]: State changed from up to starting
2021-06-25T12:26:05.819413+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-06-25T12:26:05.884707+00:00 app[worker.1]: 2021-06-25 12:26:05,884 - telegram.ext.updater - INFO - Received signal 15 (SIGTERM), stopping...
2021-06-25T12:26:09.820084+00:00 heroku[worker.1]: Starting process with command `python3 main.py`
2021-06-25T12:26:10.153466+00:00 heroku[worker.1]: Process exited with status 0
2021-06-25T12:26:10.615581+00:00 heroku[worker.1]: State changed from starting to up

What should I do?

**Comment by samadii** [comment]
Just try sending musics to the channel that you added the bot to.

**Comment by Vaibhav-08** [comment]
> Just try sending musics to the channel that you added the bot to.

Tried it, doesn't work. Moreover, In the Bot status, It shows as down.
Bot token as a sting simply means bot token right? Nothing special na?

**Comment by samadii** [comment]
Turn off the worker once and turn on, then try sending musics. 
Also note that the bot not respond in private, it only work in channels.

(Yes, 'Bot Token as a string' is same bot token.)

**Comment by Vaibhav-08** [comment]
I have added the bot to the channel and gave the bot following permissions:

![image](https://user-images.githubusercontent.com/74168340/123536584-c523b180-d748-11eb-8fdc-6efab9840361.png)

I tried turning off the worker and turning it on and It worked
But it doesn't work when I sent the track through forwarding. I guess it is because forwarded messages can't be edited. Right? and It doesn't work in groups right?

**Comment by Vaibhav-08** [comment]
Can you please tell me how to make the bot reply in PM to start command only sothat I can get its status as working in bot status and know that it is still working rather than checking it in the channel?

**Comment by samadii** [comment]
> I have added the bot to the channel and gave the bot following permissions:
> 
> ![image](https://user-images.githubusercontent.com/74168340/123536584-c523b180-d748-11eb-8fdc-6efab9840361.png)
> 
> I tried turning off the worker and turning it on and It worked
> But it doesn't work when I sent the track through forwarding. I guess it is because forwarded messages can't be edited. Right? and It doesn't work in groups right?

Yes, the forwarded messages can't be edited, and bot doesn't work in groups.

**Comment by samadii** [comment]
> Can you please tell me how to make the bot reply in PM to start command only sothat I can get its status as working in bot status and know that it is still working rather than checking it in the channel?

Good idea! i added start command.

**Comment by Vaibhav-08** [comment]
I added your changes and got this error:

2021-06-30T12:25:35.018534+00:00 app[worker]: /app/.heroku/python/lib/python3.9/site-packages/telegram/ext/conversationhandler.py:229: SyntaxWarning: "is" with a literal. Did you mean "=="?
2021-06-30T12:25:35.018686+00:00 app[worker]:   if isinstance(state, tuple) and len(state) is 2 and isinstance(state[1], Promise):

any help?

**Comment by samadii** [comment]
Maybe it be fixed by using python 3.7 , i don't really know.

**Comment by Vaibhav-08** [comment]
python 3.7 isn't out yet?

**Comment by samadii** [comment]
In fact, I'm not a coder and don't know anything.
I'm just a forker. I forked this repo from

**Comment by Vaibhav-08** [comment]
Ok

**Comment by samadii** [comment]
there is another related [repo](https://github.com/samadii/channel-musics-caption-adder),
In this one, there is no size limit.

Just note that the {album} variable can't be added in this one.

**Comment by Vaibhav-08** [comment]
I'll check but due to no album and genre, its kinda no already.
